version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.60.0
    working_directory: /tmp
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir /tmp/artifacts
      - checkout
      - run: cargo build --release
      - store_artifacts:
          path: /tmp/artifacts