version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.60.0
    steps:
      - checkout
      - run: sudo apt search golang
      # - run: cargo build --release
      # - run: mkdir /tmp/release
      # - run: ls target/release/
      # - store_artifacts:
      #     path: target/release/multit
      #     destination: multit-0.1.0