version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.60.0
    steps:
      - checkout
      - run: cargo build --release
      - run: mkdir /tmp/release
      - store_artifacts:
          path: /tmp/release