version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.60.0
    working_directory: /tmp
    steps:
      - checkout
      - run: cargo build --release
      - store_artifacts:
          path: /target/release/.multit