version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.60.0
    steps:
      - checkout
      - run: sudo apt update && sudo apt upgrade
      - run: sudo apt install -y golang
      - run: go get github.com/tcnksm/ghr
      - run: cp /home/circleci/go/bin/ghr /usr/local/bin
      - run: which ghr
      # - run: cargo build --release
      # - run: mkdir /tmp/multit && cp target/release/multit /tmp/multit
      # - run: ./home/circleci/go/bin/ghr v0.1.0 /tmp/multit